#server
server:
  port: 8080

spring:
  profiles:
    active: uat
  application:
    name: spring-test
#no data source,data source is in the dev/uat profiles


mybatis-plus:
  configuration:
#    sql print
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mybatis xml mapper location
  mapper-locations: /mapper/**/*.xml
#  set table name prefix
#  global-config:
#    db-config:
#      table-prefix:
