#server
server:
  port: 8080

spring:
  application:
    name: spring-test
#data source
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456

mybatis-plus:
  configuration:
#    sql print
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mybatis xml mapper location
  mapper-locations: /mapper/**/*.xml
#  set table name prefix
  global-config:
    db-config:
      table-prefix:
